# SQLAlchemy Models — relational persistence layer for FraudGraph.
# PostgreSQL stores the structured data (loan records, alerts, cases, audit trails)
# while Neo4j handles the graph relationships. These models define the source-of-truth
# tables that feed both the API layer and the detection engine.

from __future__ import annotations

import uuid
from datetime import date, datetime, timezone

from sqlalchemy import (
    Boolean, Date, DateTime, Enum, Float, ForeignKey, Integer, String, Text, func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all FraudGraph models."""
    pass


class LoanRecord(Base):
    """A single PPP/EIDL loan application record — the primary entity."""
    __tablename__ = "loan_records"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    borrower_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    borrower_name: Mapped[str] = mapped_column(String(256), nullable=False)
    ssn_last4: Mapped[str] = mapped_column(String(4), nullable=False)
    business_name: Mapped[str] = mapped_column(String(512), nullable=False)
    ein: Mapped[str] = mapped_column(String(12), index=True, nullable=False)
    business_address: Mapped[str] = mapped_column(String(512), nullable=False)
    business_city: Mapped[str] = mapped_column(String(128), nullable=False)
    business_state: Mapped[str] = mapped_column(String(2), nullable=False)
    business_zip: Mapped[str] = mapped_column(String(10), nullable=False)
    employee_count: Mapped[int] = mapped_column(Integer, nullable=False)
    business_age_months: Mapped[int] = mapped_column(Integer, nullable=False)
    loan_program: Mapped[str] = mapped_column(String(16), nullable=False)
    loan_amount: Mapped[float] = mapped_column(Float, nullable=False)
    loan_date: Mapped[date] = mapped_column(Date, nullable=False)
    lender_name: Mapped[str] = mapped_column(String(256), nullable=False)
    bank_routing: Mapped[str] = mapped_column(String(16), index=True, nullable=False)
    bank_account: Mapped[str] = mapped_column(String(32), nullable=False)
    naics_code: Mapped[str] = mapped_column(String(8), nullable=False)
    industry: Mapped[str] = mapped_column(String(256), nullable=False)
    fraud_label: Mapped[bool] = mapped_column(Boolean, default=False)
    fraud_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    alerts: Mapped[list["AlertRecord"]] = relationship(back_populates="loan_record")


class AlertRecord(Base):
    """An investigator-facing fraud alert generated by the detection engine."""
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    alert_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    entity_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)
    fired_rules: Mapped[str] = mapped_column(Text, nullable=False)  # JSON-encoded list
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="NEW"
    )
    triage_action: Mapped[str] = mapped_column(String(32), nullable=False)
    assigned_to: Mapped[str | None] = mapped_column(String(128), nullable=True)
    loan_record_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("loan_records.id"), nullable=True
    )
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    loan_record: Mapped["LoanRecord | None"] = relationship(back_populates="alerts")
    case: Mapped["Case | None"] = relationship(back_populates="alerts")


class Case(Base):
    """An investigation case grouping multiple related alerts."""
    __tablename__ = "cases"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="OPEN"
    )
    priority: Mapped[str] = mapped_column(String(16), nullable=False, default="MEDIUM")
    assigned_to: Mapped[str | None] = mapped_column(String(128), nullable=True)
    fraud_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    total_exposure: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    alerts: Mapped[list["AlertRecord"]] = relationship(back_populates="case")
    audit_entries: Mapped[list["AuditEntry"]] = relationship(back_populates="case")


class AuditEntry(Base):
    """Immutable audit trail entry for case actions — compliance requirement."""
    __tablename__ = "audit_entries"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=False
    )
    action: Mapped[str] = mapped_column(String(64), nullable=False)
    actor: Mapped[str] = mapped_column(String(128), nullable=False)
    details: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    case: Mapped["Case"] = relationship(back_populates="audit_entries")


class FraudRing(Base):
    """A detected fraud ring — a cluster of connected entities exhibiting coordinated fraud."""
    __tablename__ = "fraud_rings"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    ring_id: Mapped[str] = mapped_column(String(16), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    type: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="ACTIVE")
    risk_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    total_exposure: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    entity_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
